[package]
name = "apollo-client-example"
version = "0.1.0"
edition = "2024"

[dependencies]
apollo-client = { version = "0.8.1", features = ["auth"] }
env_logger = "0.11.8"
log = "0.4.26"
rust-ini = "0.21.3"
tokio = { version = "1.48.0", features = ["full"] }
url = "2.5.7"

